# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'globoplay-desafio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'

  # Pods for globoplay-desafio

  target 'globoplay-desafioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'globoplay-desafioUITests' do
    # Pods for testing
  end

end
