# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Desafio-Globoplay-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Desafio-Globoplay-iOS

  pod 'Kingfisher', '~> 7.1'
  pod 'SplashScreen', '~> 1.0'

end
